#!/bin/bash

sv start grafana || exit 1

source /etc/envvars
env


exec 2>&1

while true; do
  if [ $(curl 'http://admin:admin@localhost:3000/api/datasources' | jq '.[]|.name=="prometheus"') == "true" ]; then
    echo "prometheus already exists."
  else
    echo "adding prometheus datasource"
    curl 'http://admin:admin@localhost:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"prometheus","type":"prometheus","url":"http://localhost:9090/prometheus","access":"proxy","isDefault":true}'
  fi

sleep 30
done

