#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

sed -i -e "s|KMASTER|${KMASTER}|" /prometheus/prometheus.yml

cd /prometheus 
exec 2>&1
exec ./prometheus -config.file=/prometheus/prometheus.yml
